import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(resolve(repoRoot, "package.json"), "utf8")) as {
  dependencies: { capnweb: string };
};
const capnwebVersion = packageJson.dependencies.capnweb.replace(/^[^\d]*/, "");

const result = await build({
  absWorkingDir: repoRoot,
  bundle: true,
  entryPoints: ["src/index.ts"],
  external: [`https://esm.sh/capnweb@${capnwebVersion}`],
  format: "esm",
  keepNames: false,
  minify: false,
  platform: "browser",
  plugins: [
    {
      name: "browser-capnweb-import",
      setup(build) {
        build.onResolve({ filter: /^capnweb$/ }, () => ({
          external: true,
          path: `https://esm.sh/capnweb@${capnwebVersion}`,
        }));
      },
    },
  ],
  sourcemap: false,
  target: "es2022",
  write: false,
});

const output = result.outputFiles[0]?.text;
if (!output) throw new Error("esbuild did not produce a browser module");

await writeFile(
  resolve(repoRoot, "src/hosted/browser-module.generated.ts"),
  [
    "// Generated by scripts/build-hosted-browser-module.ts.",
    "// Do not edit by hand.",
    `export const WWW_BROWSER_MODULE = ${JSON.stringify(output)};`,
    "",
  ].join("\n"),
);
