name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
      - name: arethetypeswrong
        run: |
          pnpm pack
          mv $(ls | grep .tgz) pkg-ignoreme.tgz
          npx --yes --package @arethetypeswrong/cli@0.18.2 --package fflate@0.8.2 attw pkg-ignoreme.tgz --profile esm-only
