name: pkg.pr.new

on:
  push: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g corepack@0.31.0
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm dlx pkg-pr-new publish --pnpm --bin
